# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cliff Saporta Cheng
email: ccfcheng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Jekyll-powered blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ccfcheng.github.io" # the base hostname & protocol for your site
twitter_username: ccfcheng
github_username:  ccfcheng

timezone:    America/Los_Angeles
future:      true
highlighter: pygments
# Build settings
markdown: kramdown
